#!/bin/bash


    # global(s)
    script_dir=$( dirname $0 )
    builtin_bind="localhost:7070"


    # | function(s)

        function display_usage {
            echo "pholder usage: pholder --server [ --built-in | --vagrant ]"
        }

        function input_builtin_bind {
            if [   -z "$1" ]; then
                printf "Enter server mask [$builtin_bind]: "
                read input
            else
                input="$1"
            fi
            if [ ! -z "$input" ]; then
                builtin_bind="$input"
            fi
        }

        function start_builtin {
            php -S "$builtin_bind" -t "$script_dir/app/webroot"
        }

        function start_vagrant {
            cd "$script_dir/vagrant"
            vagrant up pholder
        }

    # function(s) |


    # | main

        # ? - argv - count
        if [ $# -eq 0 ]; then
            start_builtin
        fi

        # arg(s) - type
        case "$1" in
            '--server')
                case "$2" in
                    '--built-in')
                        input_builtin_bind "$3"
                        start_builtin
                        ;;
                    '--vagrant')
                        start_vagrant
                        ;;
                    *)
                        display_usage
                        exit 2
                        ;;
                esac
            ;;
        esac

    # main |


# pholder |
