#!/bin/bash
#
#   script - provision
#


    # export - noninteractive
    export DEBIAN_FRONTEND=noninteractive

    # set - x
    set -x


    # | apt

        # update
        apt-get update

        # upgrade
        apt-get upgrade -q -y

        # install - nginx
        apt-get install -q -y nginx

        # install - php
        apt-get install -q -y php5-fpm php5-json

        # install - extra
        apt-get install -q -y fail2ban tree

    # apt |


    # | nginx

        # update - sites-available - default
        [ -e '/tmp/etc/nginx/sites-available/default' ] && \
            cp '/tmp/etc/nginx/sites-available/default' '/etc/nginx/sites-available/default'

    # nginx |


    # | pholder
    if [ -d '/tmp/app' ]; then

        # ? - exists
        [ -d '/usr/share/nginx/pholder' ] && rm -rf '/usr/share/nginx/pholder'

        # mv - app => nginx - share
        mv '/tmp/app' '/usr/share/nginx/pholder'

    fi
    # pholder |


    # restart
    service nginx    restart
    service php5-fpm restart


    # cleanup
    [ -d '/tmp/app' ] && rm -r '/tmp/app'
    [ -d '/tmp/etc' ] && rm -r '/tmp/etc'




